#!/usr/bin/env bash

dotfiles=$HOME/dotfiles
. $dotfiles/etc/header

echo ""
info "Clean config files..."

if ! yesno "$(warn 'Are you sure you want to cleanup?')"; then
  info "Skip cleanup"
  exit 0
fi

backup=$dotfiles/backup
if [ -e $backup ]; then
  rm -rf $backup
fi
mkdir -p $backup

replace() {
  if [ -e $1 ]; then
    log "mv $1 $backup"
    mv -f $1 $backup
  fi
}

#--------------------------------------------------------------#
##        bash                                                ##
#--------------------------------------------------------------#
echo ""
info "bash"

replace $HOME/.bashrc
replace $HOME/.bash_profile

#--------------------------------------------------------------#
##        zsh                                                 ##
#--------------------------------------------------------------#
echo ""
info "zsh"

replace $HOME/.zshrc
replace $HOME/.zprofile

#--------------------------------------------------------------#
##        fish                                                ##
#--------------------------------------------------------------#
echo ""
info "fish"

replace $HOME/.config/fish

#--------------------------------------------------------------#
##        prompt                                              ##
#--------------------------------------------------------------#
echo ""
info "prompt"

replace $HOME/.zpreztorc
replace $HOME/.config/starship.toml

#--------------------------------------------------------------#
##        git                                                 ##
#--------------------------------------------------------------#
echo ""
info "git"

replace $HOME/.gitconfig
replace $HOME/.config/git
replace $HOME/.config/jesseduffield/lazygit

#--------------------------------------------------------------#
##        tmux                                                ##
#--------------------------------------------------------------#
echo ""
info "tmux"

replace $HOME/.tmux.conf
replace $HOME/.tmux.conf.local
replace $HOME/.tmux
