#!/usr/bin/env bash

dotfiles=$HOME/dotfiles
. $dotfiles/etc/header

echo ""
info "Clean config files..."

backup=$dotfiles/backup
if [ -d $backup ]; then
  rm -rf $backup
fi
mkdir -p $backup

#--------------------------------------------------------------#
##        bash                                                ##
#--------------------------------------------------------------#
echo ""
info "bash"

mv -f $HOME/.bashrc $backup
mv -f $HOME/.bash_profile $backup

#--------------------------------------------------------------#
##        zsh                                                 ##
#--------------------------------------------------------------#
echo ""
info "zsh"

mv -f $HOME/.zshrc $backup
mv -f $HOME/.zprofile $backup

#--------------------------------------------------------------#
##        fish                                                ##
#--------------------------------------------------------------#
echo ""
info "fish"

mv -f $HOME/.config/fish $backup

#--------------------------------------------------------------#
##        prompt                                              ##
#--------------------------------------------------------------#
echo ""
info "prompt"

mv -f $HOME/.zpreztorc $backup
mv -f $HOME/.config/starship.toml $backup

#--------------------------------------------------------------#
##        git                                                 ##
#--------------------------------------------------------------#
echo ""
info "git"

mv -f $HOME/.gitconfig $backup
mv -f $HOME/.config/git $backup
mv -f $HOME/.config/jesseduffield/lazygit $backup

#--------------------------------------------------------------#
##        tmux                                                ##
#--------------------------------------------------------------#
echo ""
info "tmux"

mv -f $HOME/.tmux.conf $backup
mv -f $HOME/.tmux.conf.local $backup
mv -f $HOME/.tmux $backup
